global:
  name: consul
  datacenter: AcuityDC1
  # kubectl create secret generic consul-gossip-encryption-key --from-literal=key=$(consul keygen)
  # Run above command for gossip key
  gossipEncryption:
    secretName: 'consul-gossip-encryption-key'
    secretKey: 'key'
  tls:
    enabled: true
    # This configuration sets `verify_outgoing`, `verify_server_hostname`,
    # and `verify_incoming` to `false` on servers and clients,
    # which allows TLS-disabled nodes to join the cluster.
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
server:
  replicas: 3
  bootstrapExpect: 3
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  updatePartition:
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
ui:
# Add service Loadbalancer for consul ui to be on a random port. Check in kubernetes services
# service:
#    type: "LoadBalancer"
  enabled: true
connectInject:
  enabled: true
controller:
  enabled: true
prometheus:
  enabled: true
grafana:
  enabled: true
